site_name: Tech Notes
site_url: https://iw5420.github.io/tech-notes/
site_author: Ian Wang

theme:
  name: material
  language: zh
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo   # 主色：知識感的靛藍
      accent: cyan      # 強調色：清爽的青色
      toggle:
        icon: material/weather-night
        name: 深色模式
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 淺色模式
  font:
    text: "Noto Sans TC"
    code: "Fira Code"

plugins:
  - search
  - glightbox
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iw5420
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yi-en-wang-36083b35/

extra_css:
  - stylesheets/extra.css   # 這裡引入你的自訂CSS